name: ExtendedWorlds
version: ${project.version}
main: com.gmail.supergame314.extendedworlds.ExtendedWorlds
api-version: 1.13
authors: [Super__Game]
commands:
  exw:
    description: ExtendedWorlds' command
    usage: /<command>
    permission: ExtendedWorlds.edit
permissions:
  ExtendedWorlds.edit:
    default: op